---
- hosts: 'google-refine:&apt'
  sudo: true
  tasks:
    - name: Install Google Refine dependencies
      action: apt pkg={{item}} state=present
      with_items:
        - curl     # CURL required by Refine init script
        - git      # Git to download Refine and BioVeL extension
        - openjdk-6-jdk

- hosts: google-refine
  vars:
    google_refine_install: '{{base_folder}}/GoogleRefine'
    google_refine_home: '{{base_folder}}/var/GoogleRefine'
    google_refine_log: '{{base_folder}}/var/GoogleRefine'
    google_refine_data: '{{base_folder}}/var/GoogleRefine/data'
    refine_changed:
  sudo: true
  tasks:
    - name: Create a Refine group
      group: name=refine system=yes state=present

    - name: Create a Refine user account
      user: >
        name=refine
        comment='Refine service'
        group=refine
        system=yes
        createhome=no
        home={{google_refine_home}}
        state=present

    - name: create Google Refine home directory
      file: >
        path={{google_refine_home}}
        state=directory
        owner=refine

    - name: Create Google Refine install directory
      file: >
        path={{google_refine_install}}
        state=directory
        owner=refine

    - name: Clone Google Refine code from Github
      sudo_user: refine
      git: >
        repo=https://github.com/OpenRefine/OpenRefine.git
        dest={{google_refine_install}}/OpenRefine
        version=tags/v1.0.7

    - name: Clone Refine BioVeL extension code from Github
      sudo_user: refine
      git: >
        repo=https://github.com/BioVeL/refine-ext.git
        dest={{google_refine_install}}/refine-ext
        version=afd58db14f03229e46fc8e8e340cade1aef801d5

    - name: Create a link to extension
      sudo_user: refine
      file: >
        state=link
        src={{google_refine_install}}/refine-ext
        dest={{google_refine_install}}/OpenRefine/extensions/biovel

    - name: Add BioVeL extension build to OpenRefine
      sudo_user: refine
      lineinfile: >
        dest={{google_refine_install}}/OpenRefine/extensions/build.xml
        insertafter='<echo message="Building extensions" />'
        line='    <ant dir="biovel/" target="build" />'
        state=present
        backup=yes

    - name: Add BioVeL extension clean to OpenRefine
      sudo_user: refine
      lineinfile: >
        dest={{google_refine_install}}/OpenRefine/extensions/build.xml
        insertafter='<echo message="cleaning extensions" />'
        line='    <ant dir="biovel/" target="clean" />'
        state=present

    - name: Build OpenRefine
      sudo_user: refine
      shell: >
        JAVA_HOME=/usr/lib/jvm/java-6-openjdk-amd64
        ./refine build
        chdir={{google_refine_install}}/OpenRefine

    - name: Create refine start script
      template: >
        src=start-refine.j2
        dest={{google_refine_install}}/OpenRefine/start-refine
        owner=refine  mode=0755

    - name: create Google Refine log directory
      file: path={{google_refine_log}} state=directory owner=refine

    - name: create Google Refine data directory
      file: path={{google_refine_data}} state=directory owner=refine

    - name: setup Google Refine init script
      template: >
        src=refine-initd.j2
        dest=/etc/init.d/refine
        owner=root  group=root  mode=0755

  handlers:
    - name: Restart Google Refine
      # actually, just stop service, as the start below will restart it
      service: name=refine state=stopped

# For systems that use update-rc.d, run the command manually to enable starting on reboot
- hosts: 'google-refine:&apt'
  sudo: true
  tasks:
    - name: Start Google Refine on reboot
      command: update-rc.d refine defaults

# For other systems, use the service module.
- hosts: 'google-refine:!apt'
  sudo: true
  tasks:
    - name: Start Google Refine on reboot
      service: name=refine enabled=yes

- hosts: google-refine
  sudo: true
  tasks:
    - name: Start Google Refine service
      service: name=refine state=started

