---
language: python
python: "2.7"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qqy gawk curl
  - pip install ansible

script:
  # Check the playbook's syntax.
  - "ansible-playbook -i inventory/hosts-testing playbooks/site.yaml --syntax-check"
