---
- hosts: "biovel-portal:&apt"
  sudo: yes
  tasks:
    - name: "Install portal package dependencies"
      action: apt pkg={{ item }} state=present
      with_items:
        - libcurl4-gnutls-dev
        - libxml2-dev
        - libv8-dev
        - ruby
        - ruby-dev
        - ri
        - rubygems
        - git            # to obtain portal source code
        - python-mysqldb # required for Ansible mysql modules

- hosts: biovel-portal
  sudo: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: Install Ruby gem bundler
      gem: name=bundler state=present

    - name: Add BioVeL Portal database
      mysql_db: name={{item}} state=present
      with_items:
        - tlite_test
        - tlite_dev
        - tlite_prod

    - name: Add BioVeL Portal database user
      mysql_user: name={{biovel_portal['db_user']}} password={{biovel_portal['db_pass']}} state=present
            "priv=tlite_prod.*:ALL/tlite_dev.*:ALL/tlite_test.*:ALL"

    - name: Create portal install directory
      file: name={{portal_install}} state=directory owner=www-data

    - name: create Portal log directory
      file: path={{portal_log}} state=directory owner=www-data

    - name: Get portal code
      sudo_user: www-data
      git: repo=https://github.com/BioVeL/portal.git dest={{portal_install}} version=0.3.7-maint
      notify: restart portal

    - name: install Ruby dependencies using bundle
      # this command is effectively idempotent, as it does not do anything if the dependencies
      # are already installed, and it is fast when nothing needs to be done
      command: bundle install
          chdir={{portal_install}}

    - name: configure portal database connections
      sudo_user: www-data
      template: src=database.yml.j2 dest={{portal_install}}/config/database.yml mode=0600

    - name: precompile assets
      # TODO - assets only get precompiled when application.js does not exist - it would be nice to
      # re-run it when the Git repository gets updated
      sudo_user: www-data
      command: bundle exec rake assets:precompile
          chdir={{portal_install}} creates={{portal_install}}/public/assets/application.js

    - name: setup databases
      sudo_user: www-data
      command: bundle exec rake RAILS_ENV={{item}} db:migrate chdir={{portal_install}}
      with_items:
        - development
        - production

    - name: setup for database completion
      template: src=dbcreate.sh.j2 dest={{portal_install}}/dbcreate.sh owner=root mode=0700

    - name: run setup for databases
      command: "{{portal_install}}/dbcreate.sh {{item}}"
      with_items:
        - tlite_dev
        - tlite_prod 

    # TODO - we need to ensure these daemons are started at boot time
    # we also need to restart them if they are running. Easiest is just to
    # stop them start them. Stopping them if they are already stopped is OK.
    - name: stop daemons
      sudo_user: www-data
      command: rake RAILS_ENV=production daemons:stop
          chdir={{portal_install}}

    - name: start daemons
      sudo_user: www-data
      command: rake RAILS_ENV=production daemons:start
          chdir={{portal_install}}

    - name: install Passenger
      gem: name=passenger state=present

    - name: install Passenger into Apache
      shell: yes | passenger-install-apache2-module
          creates=/etc/apache2/mods-available/passenger.load
      # The output is almost unreadable due to extensive use of control characters
      # so we run two additional commands below to work out the correct values
      #register: passenger_apache

    - name: find Passenger base directory
      shell: ls -d /var/lib/gems/1.8/gems/passenger-*
      register: passenger_base

    - name: find Passenger module
      command: find {{passenger_base.stdout}} -name mod_passenger.so
      register: passenger_module

    - name: add Passenger configuration
      template: src={{item}}.j2 dest=/etc/apache2/mods-available/{{item}}
      with_items:
        - passenger.load
        - passenger.conf

    - name: enable Passenger module
      command: a2enmod passenger
          creates=/etc/apache2/mods-enabled/passenger.load
      notify: restart portal

    - name: add Virtual Host to Apache
      template: src=vhost.j2 dest=/etc/apache2/sites-available/tlite
      notify: restart portal

    - name: disable default site
      command: a2dissite default
          removes=/etc/apache2/sites-enabled/000-default
      notify: restart portal

    - name: enable Portal site
      command: a2ensite tlite
          creates=/etc/apache2/sites-enabled/tlite
      notify: restart portal

  handlers:
    - name: restart portal
      service: name=apache2 state=restarted
