---
- hosts: "biovel-portal:&apt"
  sudo: yes
  tasks:
    - name: "Install portal run dependencies"
      action: apt pkg={{ item }} state=present
      with_items:
        - libcurl4-gnutls-dev
        - libxml2-dev
        - libv8-dev

    - name: "Install Ruby ecosystem"
      action: apt pkg={{ item }} state=present
      with_items:
        - ruby
        - ruby-dev
        - ri
        - rubygems

    - name: "Install portal installation dependencies"
      action: apt pkg={{ item }} state=present
      with_items:
        - git            # to obtain portal source code
        - python-mysqldb # required for Ansible mysql modules

- hosts: biovel-portal
  sudo: yes
  vars_files:
    - vars.yaml
    - vars-database.yaml
  tasks:
    - name: Install Ruby gem bundler
      gem: name=bundler state=present

    - name: Add BioVeL Portal database
      mysql_db: name={{item}} state=present
      with_items:
        - tlite_test
        - tlite_dev
        - tlite_prod

    - name: Add BioVeL Portal database user
      mysql_user: name={{db_user}} password={{db_pass}} state=present
            "priv=tlite_prod.*:ALL/tlite_dev.*:ALL/tlite_test.*:ALL"

    - name: Create portal install directory
      file: name={{portal_install}} state=directory owner=www-data

    - name: create Portal log directory
      file: path={{portal_log}} state=directory owner=www-data

    - name: Get portal code
      sudo_user: www-data
      git: repo=https://github.com/BioVeL/portal.git dest={{portal_install}} version=0.3.7-maint
      notify: restart portal

    - name: install Ruby dependencies using bundle
      command: bundle install chdir={{portal_install}}

    - name: configure portal database connections
      sudo_user: www-data
      template: src=database.yml.j2 dest={{portal_install}}/config/database.yml

    - name: precompile assets
      sudo_user: www-data
      command: bundle exec rake assets:precompile chdir={{portal_install}}

    # this seems to not clobber the existing database, which is good
    # # but what happens if the schema changes?
    - name: setup databases
      sudo_user: www-data
      command: bundle exec rake RAILS_ENV={{item}} db:migrate chdir={{portal_install}}
      with_items:
        - development
        - production

    # TODO - we need to ensure these daemons are started at boot time
    # we also need to only run this if the daemons are not already running
    - name: start daemons
      sudo_user: www-data
      command: rake RAILS_ENV=production daemons:start chdir={{portal_install}}

    - name: install Passenger
      gem: name=passenger state=present

    - name: install Passenger into Apache
      shell: yes | passenger-install-apache2-module
      register: passenger_apache

    - name: add Passenger configuration
      copy: src={{item}} dest=/etc/apache2/mods-available/
      with_items:
        - passenger.load
        - passenger.conf

    - name: enable Passenger module
      command: a2enmod passenger creates=/etc/apache2/mods-enabled/passenger.load
      notify: restart portal

    - name: add Virtual Host to Apache
      template: src=vhost.j2 dest=/etc/apache2/sites-available/tlite
      notify: restart portal

    - name: disable default site
      command: a2dissite default removes=/etc/apache2/sites-enabled/000-default
      notify: restart portal

    - name: enable Portal site
      command: a2ensite tlite creates=/etc/apache2/sites-enabled/tlite
      notify: restart portal

  handlers:
    - name: restart portal
      service: name=apache2 state=restarted
