---
# R packages for Metagenomics Traits Analysis workflow
- hosts: rserve
  sudo: yes
  tasks:
    - name: Install R packages from CRAN
      shell: echo "options(repos=structure(c(CRAN='{{ cran_repository }}/')));if(require({{ item }})){}else{install.packages('{{ item }}')}" | /usr/bin/R --no-save
      with_items:
        - vegan
        - ape
        - MASS
        - ggplot2
