---
- hosts: oracle-java-jre:&apt
  sudo: true
  tasks:
    - name: Add package python-software-properties
      apt: pkg=python-software-properties state=present

    - name: Add deb repository for update-sun-jre
      apt_repository: "repo='deb http://www.duinsoft.nl/pkg debs all'"
      notify: Update apt repository

    - name: Add repository key
      apt_key: "id=5CB26B26 url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x5CB26B26 state=present"
      notify: Update apt repository

  handlers:
    - name: Update apt repository
      apt: update_cache=yes

- hosts: oracle-java-jre:&apt
  sudo: true
  tasks:
    - name: Install Oracle JRE
      apt: pkg=update-sun-jre state=present

- hosts: oracle-java-jre
  sudo: true
  tasks:
    - name: Get JRE path
      shell: ls -d /opt/java/64/jre1.7.0* | tail -1
      register: oracle_jre_ls

    - name: Set JRE path
      set_fact: oracle_jre_path="{{oracle_jre_ls.stdout}}"

    - name: Copy JCE local policy file
      copy: src=JCE/UnlimitedJCEPolicy/local_policy.jar dest={{oracle_jre_path}}/lib/security/local_policy.jar backup=yes

    - name: Copy JCE US export policy file
      copy: src=JCE/UnlimitedJCEPolicy/US_export_policy.jar dest={{oracle_jre_path}}/lib/security/US_export_policy.jar backup=yes
