---
- hosts: apache-tomcat6:&apt
  sudo: yes
  tasks:

    - name: Install Tomcat 6
      apt: pkg={{item}} state=present
      with_items:
        # Tomcat complains on start if there is no JDK installed, but on Ubuntu
        # 12.04 there is no JDK listed in its dependencies, so install a JDK
        # manually.
        - default-jdk
        - tomcat6

- hosts: apache-tomcat6
  sudo: yes
  tasks:

    - name: Increase Tomcat memory
      lineinfile: dest=/etc/default/tomcat6 regexp='^(JAVA_OPTS=.*-Xmx)\d+[MmGg]?(.*)$' line='\g<1>1024m\g<2>'
            state=present backrefs=yes backup=yes
      notify: Restart Tomcat

  handlers:

    - name: Restart Tomcat
      service: name=tomcat6 state=restarted