---
- hosts: apache-tomcat6:&apt
  sudo: yes
  tasks:

    - name: Install Tomcat 6
      apt: pkg={{item}} state=present
      with_items:
        - tomcat6

- hosts: apache-tomcat6
  sudo: yes
  tasks:

    - name: Increase Tomcat memory
      lineinfile: dest=/etc/default/tomcat6 regexp='^(JAVA_OPTS=.*-Xmx)\d+[MmGg]?(.*)$' line='\g<1>1024m\g<2>'
            state=present backrefs=yes backup=yes
      notify: Restart Tomcat

    - name: Use Orcale JRE 1.7
      lineinfile: dest=/etc/default/tomcat6 insertafter='^#JAVA_HOME' line='JAVA_HOME=/opt/java/64/jre1.7.0_51'
            state=present backup=yes
      notify: Restart Tomcat

  handlers:

    - name: Restart Tomcat
      service: name=tomcat6 state=restarted
