---
- hosts: apache-tomcat6:&apt
  sudo: yes
  tasks:

    - name: Install Tomcat 6
      apt: pkg=tomcat6 state=present

- hosts: apache-tomcat6
  sudo: yes
  tasks:

    - name: Create Tomcat web.xml with WebDAV enabled
      template: src=web.xml.j2 dest=/etc/tomcat6/web.xml owner=root group=tomcat6 mode=0644 backup=yes 
      notify: Restart Tomcat

    - name: allow WebDAV to use ROOT directory for serving files
      file: name=/var/lib/tomcat6/webapps/ROOT state=directory owner=tomcat6 mode=0750

  handlers:

    - name: Restart Tomcat
      service: name=tomcat6 state=restarted