---
- hosts: rbase
  tasks:
    - group_by: key=rOn{{ansible_distribution}}

# On Ubuntu 12.04 ("precise") the standard repositories provide R 2.14
# We require R 2.15, because e.g. [package popbio] requires [package quadprog] requires [R 2.15]
# Up-to-date packages are maintained in a separate repository, which we add here.
# The Ansible apt_repository module requires the apt-add-repository command from 
# package python-software-properties
- hosts: rOnUbuntu
  sudo: yes
  tasks:
    - name: Add package python-software-properties
      apt: pkg=python-software-properties state=present

    - name: Add Ubuntu repository for R
      apt_repository: "repo='deb {{cran_repository}}/bin/linux/ubuntu {{ansible_distribution_release}}/'"
      notify: Update apt repository

    - name: Add repository key
      apt_key: "id=E084DAB9 url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xE084DAB9 state=present"
      notify: Update apt repository

  handlers:
    - name: Update apt repository
      apt: update_cache=yes

# Linux Mint is a version of Ubuntu, but we need to translate the distribution names.
# We can't support the distributions between Isadora and Maya because the dependency liblzma[1-5]
# changed its name rapidly during these versions of the OS - Isadora requires liblzma1, Maya
# requires liblzma5, and the intermediate OS's require intermediate versions of liblzma
- hosts: rOnLinuxmint
  sudo: yes
  vars_files:
    - [ "mint_{{ansible_distribution_release}}.yaml", "mint_default.yaml" ]
  tasks:
    - name: Add package python-software-properties
      when: ubuntu_dist != "none"
      apt: pkg=python-software-properties state=present

    - name: Add Ubuntu repository for R
      when: ubuntu_dist != "none"
      apt_repository: "repo='deb {{cran_repository}}/bin/linux/ubuntu {{ubuntu_dist}}/'"
      notify: Update apt repository

    - name: Add repository key
      when: ubuntu_dist != "none"
      apt_key: "id=E084DAB9 url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0xE084DAB9 state=present"
      notify: Update apt repository

  handlers:
    - name: Update apt repository
      apt: update_cache=yes

- hosts: rbase:&apt
  sudo: yes
  tasks:

    # This fact is used to create an inter-play handler. Anything which changes the state of the R
    # installation can set this fact to True to cause dependencies to restart.  This means we don't
    # need to know whether this machine is running Rserve or OpenCPU servers yet.
    - name: Setup R facts
      set_fact: r_changed=False

    - name: Install R
      action: apt pkg={{item}} state=present
      with_items:
        - r-base
        - r-base-dev
        - r-recommended
      notify: R changed

  handlers:
    - name: R changed
      set_fact: r_changed=True    
