---
- hosts: rserve:&apt
  sudo: yes
  tasks:

    - name: Install Rserve
      action: apt pkg={{item}} state=present
      with_items:
        - r-cran-rserve

- hosts: rserve
  sudo: yes
  tasks:
    - name: Create an Rserve group
      group: name=rserve system=yes state=present

    - name: Create an Rserve user account
      user: name=rserve comment="Rserve service" group=rserve system=yes createhome=no state=present

    - name: Get Rserve user and group ids
      shell: "getent passwd rserve | cut -d: -f3-4"
      register: rserve_id

    - name: Create Rserve configuration file
      template: src=Rserv.conf.j2 dest=/etc/Rserv.conf owner=root group=root mode=0644
      notify: Restart Rserve

    - name: Create Rserve password file
      template: src=Rserv.pass.j2 dest=/etc/Rserv.pass owner=root group=root mode=0600
      notify: Restart Rserve

    - name: Create Rserve init script
      copy: src=rserve-initd dest=/etc/init.d/rserve owner=root group=root mode=0755
      notify: Restart Rserve

    # The handler for service enabled on Ubuntu 12.04 using update-rc.d is broken.
    # It doesn't ensure the links are created for enable to work, and it's parsing
    # of the output for update-rc.d is too specific to one version.
    #- name: Start Rserve on reboot
    #  service: name=rserve enabled=yes
  handlers:
    - name: Restart Rserve
      set_fact: r_changed=True

- hosts: rserve
  sudo: yes
  tasks:
    - name: Restart R server
      service: name=rserve state=stopped
      when: r_changed

    # If R changed, these two commands perform a restart of the R server. If R
    # did not change, then we simply ensure that the R server is running and
    # start if it not.
    - name: Ensure Rserve is running
      service: name=rserve state=started

# For systems that use update-rc.d, run the command manually to enable starting on reboot
- hosts: rserve:&apt
  sudo: yes
  tasks:
    - name: Start Rserve on reboot
      command: update-rc.d rserve defaults

# For other systems, use the service module.
- hosts: rserve:!apt
  sudo: yes
  tasks:
    - name: Start Rserve on reboot
      service: name=rserve enabled=yes
