#!/bin/sh
#
# /etc/init.d/rserve -- startup script for the Rserve service
#
### BEGIN INIT INFO
# Provides:          rserve
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manage Rserve.
# Description:       Manage the Rserve service.
### END INIT INFO

set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin

case "$1" in
  start)
	start-stop-daemon --start --oknodo --name Rserve --exec /usr/bin/R -- CMD Rserve --vanilla
	;;
  stop)
	start-stop-daemon --stop --oknodo --name Rserve
	;;
  restart)
	$0 stop
	$0 start
	;;
  status)
	start-stop-daemon --status --name Rserve
	;;
  *)
	log_success_msg "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

exit 0
