---
# BioVeL portal needs to be able to send email - just setup default sendmail for now
- hosts: biovel-portal:&apt
  sudo: true
  tasks:
    - name: Install sendmail
      apt: pkg=sendmail state=latest

    - include: gmail.yml
      when: "'{{biovel_portal_gmail_pass}}' != 'biovel'"
