---
# R packages for Sound Analysis workflows
- hosts: rserve:&apt
  sudo: true
  tasks:
    - name: Install FFTW3 and SndFile libraries
      action: apt pkg={{item}} state=present
      with_items:
        - fftw3-dev
        - libsndfile1-dev

- hosts: rserve
  sudo: true
  tasks:
    - name: Install R packages from CRAN
      shell: echo "options(repos=structure(c(CRAN='{{ cran_repository }}/')));if(require({{ item }})){}else{install.packages('{{ item }}');library({{ item }})}" | /usr/bin/R --no-save
      with_items:
        - seewave
      notify: R changed

  handlers:
    - name: R changed
      set_fact: r_changed=True
