---
# R packages for whale population modelling workflow
- hosts: rserve
  sudo: yes
  tasks:
    - name: Install R packages from CRAN
      shell: echo "options(repos=structure(c(CRAN='{{ cran_repository }}/')));if(require({{ item }})){}else{install.packages('{{ item }}')}" | /usr/bin/R --no-save
      with_items:
        - betareg
      notify: R changed

  handlers:
    - name: R changed
      set_fact: r_changed=True