---
- hosts: taverna-server
  sudo: yes
  vars_files:
    - vars.yaml
  tasks:
    - name: Create Atomhopper install directory
      file: path={{ah_install}} state=directory

    - name: Download AtomHopper
      get_url: url=http://maven.research.rackspacecloud.com/content/repositories/releases/org/atomhopper/ah-war/0.9.10/ah-war-0.9.10.war
            dest={{ah_install}}/atomhopper.war

    - name: Unpack AtomHopper
      command: unzip {{ah_install}}/atomhopper.war -d {{ah_install}} creates={{ah_install}}/META-INF

    - name: Create Atomhopper configuration directory
      file: path=/etc/atomhopper state=directory

    - name: copy AtomHopper configuration files
      template: src={{item}}.j2 dest=/etc/atomhopper/{{item}} owner=root group=root mode=0644
      with_items:
        - application-context.xml
        - atom-server.cfg.xml
        - log4j.properties
      notify: Restart Tomcat

    - name: create AtomHopper database directory
      file: path={{ah_lib} state=directory owner=tomcat6

    - name: create AtomHopper log directory
      file: path={{ah_log}} state=directory owner=tomcat6

    # logger likes log file to exist
    - name: create AtomHopper log file
      sudo_user: tomcat6
      command: touch {{ah_log}}/ah.log creates={{ah_log}}/ah.log

    - name: create AtomHopper context in Tomcat
      template: src=ah.xml.j2 dest=/etc/tomcat6/Catalina/localhost/ah.xml owner=tomcat6
      notify: Restart Tomcat

  handlers:
    - name: Restart Tomcat
      service: name=tomcat6 state=restarted