---
# this play adds SSL to a portal after initial installation.
# We could probably just run site.yaml again, but we would need to ensure
# all passwords were set correctly, etc.
- hosts: amazon
  tasks:
    - name: Get EC2 facts
      action: ec2_facts

- hosts: all
  tasks:
    - group_by: key={{ ansible_pkg_mgr }}

- include: core/ntp/ntp.yaml
- include: external-ip/external-ip.yaml
- include: apache-httpd/httpd.yaml
- include: biovel/portal/postssl.yaml
