---
- hosts: amazon
  tasks:
    - name: Get EC2 facts
      action: ec2_facts

- hosts: all
  tasks:
    - group_by: key={{ ansible_pkg_mgr }}

- hosts: apt
  sudo: yes
  tasks:
    - name: Update apt repository
      apt: update_cache=yes cache_valid_time=3600

- include: core/ntp/ntp.yaml
# Everything needed for Rserve and workflow dependencies
# Currently, the workflow dependencies are between r-base and rserve
# so that R packages exist when Rserve is started
- include: rserve/rbase.yaml
- include: biovel/workflows/ipm.yaml
- include: biovel/workflows/mpm.yaml
- include: biovel/workflows/mta.yaml
- include: biovel/workflows/osd.yaml
- include: biovel/workflows/psw.yaml
- include: biovel/workflows/whales.yaml
- include: rserve/rserve.yaml
# Taverna Workbench
- include: oracle-java/jre.yaml
- include: taverna-workbench/workbench.yaml
# Common to Taverna Server and BioVeL Portal
- include: external-ip/external-ip.yaml
# Everything needed for Taverna Server
- include: unzip/unzip.yaml
- include: apache-tomcat6/tomcat6.yaml
- include: atomhopper/atomhopper.yaml
- include: taverna-server/tserver.yaml
# Everything needed for DRW workflow
- include: google/refine/refine.yaml
- include: biovel/workflows/drw.yaml
# Everything needed for BioVeL Portal
- include: mail-transfer/sendmail.yml
- include: mysql/mysql-server.yaml
- include: apache-httpd/httpd.yaml
- include: biovel/portal/portal.yaml