---
- hosts: apache-httpd:&apt
  sudo: yes
  tasks:
  
    - name: Install Apache web server
      apt: pkg={{item}} state=present
      with_items:
        - apache2
        - apache2-threaded-dev

- hosts: apache-httpd
  sudo: yes
  tasks:

    - include: ssl.yaml
      when: apache_https["hostname"] != 'none'

  handlers:
    - name: stop Apache for reconfiguration
      service: name=apache2 state=stopped

- hosts: apache-httpd
  sudo: yes
  tasks:
    - name: ensure Apache is running
      service: name=apache2 state=started 